FitWord/Areas/Customer/Controllers/MealsController.cs
using FitWord.Models;
using FitWorld.Database;
using FitWorld.Database.Repository;
using FitWorld.Models.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;

namespace FitWord.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class MealsController : Controller
    {
        private readonly IUnitOfWork _db;
        private readonly UserManager<ApplicationUser> _userManager;
        

        public MealsController(IUnitOfWork db, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            
            List<Meal> meals = (List<Meal>)_db.Meal.GetAll();
            if (meals != null)
            {
                return View(meals);
            }
            else
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
           
        }

        public IActionResult ShowMeal(int id)
        {
            Meal ?meal = _db.Meal.Find(id);
            if (meal != null)
            {
                return View(meal);
            }
            else
            {
                return RedirectToAction("Index");
            }
            
        }

        public IActionResult Add()
        {
            return View();
        }
        public IActionResult Edit(int id)
        {
            Meal? meal = _db.Meal.Find(id);
           
                return View(meal);
           
          
                
            
        }
        public IActionResult DownloadPdf(int mealId)
        {
            var meal = _db.Meal.Find(mealId);

            if (meal != null && meal.pdfMeal != null)
            {
                return File(meal.pdfMeal, "application/pdf", "Meal.pdf");
            }
            else
            {
                // Obsługa przypadku, gdy plik nie istnieje
                return NotFound();
            }
        }
        [HttpPost]
        public async Task<IActionResult> Add(Meal meal, IFormFile pdfMeal)
        {
            var memoryStream = new MemoryStream();
            pdfMeal.CopyTo(memoryStream);
            meal.pdfMeal = memoryStream.ToArray();
            var user = await _userManager.GetUserAsync(User);
            meal.MealOwnerId = user.Id;
            _db.Meal.Add(meal);
            _db.Save();
            return RedirectToAction("Index");
           
           
        }

        [HttpPost]
        public IActionResult Delete(Meal obj) {
            
            int id = (int)obj.mealId;
            Meal meal= _db.Meal.Find(id);
            _db.Meal.Delete(meal);
            _db.Save();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(Meal obj)
        {
            
            _db.Meal.Update(obj);
            _db.Save();
            return RedirectToAction("Index");
        }
    }
}

FitWord/Areas/Customer/Controllers/PlansController.cs
using FitWord.Models;
using FitWorld.Database;
using FitWorld.Database.Repository;
using FitWorld.Models.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FitWord.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class PlansController : Controller
    {
        private  IUnitOfWork _db {  get; set; }
        private readonly UserManager<ApplicationUser> _userManager;
        public PlansController(IUnitOfWork db, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            
            List<Plan> plans = (List<Plan>)_db.Plan.GetAll();
            if(plans==null || plans.Count == 0)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            return View(plans);
        }

        public IActionResult ShowPlan(int id)
        {
            Plan plan = _db.Plan.Find(id);
            if (plan == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            return View(plan);
        }
        public IActionResult Add()
        {
            return View();
        }

        public IActionResult DownloadPdf(int planId)
        {
            var plan = _db.Plan.Find(planId);

            if (plan != null && plan.pdfPlan != null)
            {
                return File(plan.pdfPlan, "application/pdf", "Meal.pdf");
            }
            else
            {
                // Obsługa przypadku, gdy plik nie istnieje
                return NotFound();
            }
        }

        public IActionResult Edit(int id)
        {
            Plan plan = _db.Plan.Find(id);
            if (plan == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            return View(plan);
        }

        [HttpPost]
        public async Task<IActionResult> Add(Plan plan,IFormFile pdfPlan)
        {
            var memoryStream = new MemoryStream();
            pdfPlan.CopyTo(memoryStream);
            plan.pdfPlan = memoryStream.ToArray();
            var user = await _userManager.GetUserAsync(User);
            plan.PlanOwnerId = user.Id;
            _db.Plan.Add(plan);
            _db.Save();
            return RedirectToAction("Index");  
        }

        [HttpPost]
        public IActionResult Edit(Plan plan)
        {
           
            _db.Plan.Update(plan);
            _db.Save();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Delete(Plan plan)
        {
            
            Plan planToDelete =_db.Plan.Find(plan.planId);
            _db.Plan.Delete(planToDelete);
            _db.Save();
            return RedirectToAction("Index");
        }
    }
}

FitWord/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FitWord</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FitWord.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/style.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-dark bg-dark pt-4 pt-sm-2  pb-0 ">
            <div class="container-fluid">
                <a class="navbar-brand brand-text" asp-area="" asp-controller="Home" asp-action="Index">FitWorld</a>
                <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-lg-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            
                            <a class="nav-link custom-main-text" asp-area="" asp-controller="Home" asp-action="Index">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 19 19">
                                    <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z" />
                                </svg>
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link custom-main-text" asp-area="" asp-controller="Plans" asp-action="Index">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-card-list" viewBox=" 0 0  19 19">
                                    <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2z" />
                                    <path d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8m0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5m0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5m-1-5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0M4 8a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m0 2.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0" />
                                </svg>
                                Training Plans
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link custom-main-text" asp-area="" asp-controller="Meals" asp-action="Index">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-egg-fried" viewBox="0 0 20 20">
                                    <path d="M8 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6" />
                                    <path d="M13.997 5.17a5 5 0 0 0-8.101-4.09A5 5 0 0 0 1.28 9.342a5 5 0 0 0 8.336 5.109 3.5 3.5 0 0 0 5.201-4.065 3.001 3.001 0 0 0-.822-5.216zm-1-.034a1 1 0 0 0 .668.977 2.001 2.001 0 0 1 .547 3.478 1 1 0 0 0-.341 1.113 2.5 2.5 0 0 1-3.715 2.905 1 1 0 0 0-1.262.152 4 4 0 0 1-6.67-4.087 1 1 0 0 0-.2-1 4 4 0 0 1 3.693-6.61 1 1 0 0 0 .8-.2 4 4 0 0 1 6.48 3.273z" />
                                </svg>
                                Diet Meals
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link custom-main-text" asp-area="" asp-controller="Home" asp-action="FitWorldPremium">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-currency-dollar" viewBox="0 0 19 19">
                                    <path d="M4 10.781c.148 1.667 1.513 2.85 3.591 3.003V15h1.043v-1.216c2.27-.179 3.678-1.438 3.678-3.3 0-1.59-.947-2.51-2.956-3.028l-.722-.187V3.467c1.122.11 1.879.714 2.07 1.616h1.47c-.166-1.6-1.54-2.748-3.54-2.875V1H7.591v1.233c-1.939.23-3.27 1.472-3.27 3.156 0 1.454.966 2.483 2.661 2.917l.61.162v4.031c-1.149-.17-1.94-.8-2.131-1.718H4zm3.391-3.836c-1.043-.263-1.6-.825-1.6-1.616 0-.944.704-1.641 1.8-1.828v3.495l-.2-.05zm1.591 1.872c1.287.323 1.852.859 1.852 1.769 0 1.097-.826 1.828-2.2 1.939V8.73l.348.086z" />
                                </svg>
                                FitWorld Premium
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
            
        </nav>
        <div class="wave">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#212529" fill-opacity="1" d="M0,32L40,37.3C80,43,160,53,240,53.3C320,53,400,43,480,42.7C560,43,640,53,720,48C800,43,880,21,960,10.7C1040,0,1120,0,1200,10.7C1280,21,1360,43,1400,53.3L1440,64L1440,0L1400,0C1360,0,1280,0,1200,0C1120,0,1040,0,960,0C880,0,800,0,720,0C640,0,560,0,480,0C400,0,320,0,240,0C160,0,80,0,40,0L0,0Z"></path></svg>
        </div>
        
    </header>
    
    <div class=" container h-100">
        
            @RenderBody()
        
    </div>

    
    <footer class="footer text-muted bg-dark border-top-1">
        <div class="main-footer row container-sm  pt-sm-3 pt-smmd-3  justify-content-sm-around">
            <div class="data col-6">
                <h3 class="t-primary">Our socials</h3>
                <a class="social">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951" />
                    </svg>
                    Facebook
                </a>
                
                <a class="social">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                        <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334" />
                    </svg>
                    Instagram
                </a>
                
                <a class="social">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
                        <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865l8.875 11.633Z" />
                    </svg>
                    Twitter
                </a>
                
                <a class="social">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-messenger" viewBox="0 0 16 16">
                        <path d="M0 7.76C0 3.301 3.493 0 8 0s8 3.301 8 7.76-3.493 7.76-8 7.76c-.81 0-1.586-.107-2.316-.307a.639.639 0 0 0-.427.03l-1.588.702a.64.64 0 0 1-.898-.566l-.044-1.423a.639.639 0 0 0-.215-.456C.956 12.108 0 10.092 0 7.76m5.546-1.459-2.35 3.728c-.225.358.214.761.551.506l2.525-1.916a.48.48 0 0 1 .578-.002l1.869 1.402a1.2 1.2 0 0 0 1.735-.32l2.35-3.728c.226-.358-.214-.761-.551-.506L9.728 7.381a.48.48 0 0 1-.578.002L7.281 5.98a1.2 1.2 0 0 0-1.735.32z" />
                    </svg>
                    Messenger
                </a>
            </div>
            <div class="contact col-6">
                <h2 class="t-primary">Contact Us</h2>
                <p class="t-primary">
                    john.doe@example.com
                </p>
                <p class="t-primary">
                    +1 (555) 123-4567
                </p>
                <p class="t-primary">
                    123 Main Street
                </p>
                <p class="t-primary">
                    Anytown
                </p>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>